# Generated by Django 4.1.3 on 2024-01-28 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("memorify_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="rolodex",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="rolodex",
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Rolodex",
        ),
    ]
