# Generated by Django 4.1.3 on 2024-01-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "memorify_app",
            "0002_remove_contact_rolodex_remove_useraccount_rolodex_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
