from llm_ai import LLM_AI

llm_ai = LLM_AI()

journal_entry = "Journal Entry - January 26, 2024\n\nJohn likes basketball.Today was a day filled with laughter, discussions, and shared moments with my close friends. As we gathered in the cozy living room, the atmosphere was buzzing with positive energy. The warmth of friendship enveloped us, creating a sense of comfort and belonging.\n\nIn the morning, Sarah and I decided to explore a new coffee shop in the neighborhood. The aroma of freshly brewed coffee and the sound of soft chatter created the perfect backdrop for catching up on each other's lives. Sarah shared her recent travel adventures, and we exchanged stories about our individual pursuits and aspirations.\n\nLater in the day, John and Mark joined us for a spontaneous picnic at the nearby park. The sun was shining brightly, and we found a perfect spot under the shade of a large oak tree. As we laid out the picnic blanket, the laughter and camaraderie flowed effortlessly. We indulged in delicious snacks, played card games, and reminisced about the memorable experiences we've shared over the years.\n\nIn the evening, our group expanded as we welcomed Emily and Alex for a homemade dinner at my place. Cooking together became an opportunity for creative collaboration, with each person contributing their culinary skills. The kitchen was alive with the sizzle of ingredients and the aroma of our combined efforts.\n\nAs we sat around the dining table, the conversation delved into deeper topics. We discussed our dreams, challenges, and the unwavering support we've provided for one another. The bond of friendship became more profound as we shared vulnerabilities and celebrated each other's successes.\n\nThe day concluded with a movie night, where we picked a classic film that held sentimental value for all of us. The shared experience of laughter, tears, and genuine emotions created a lasting memory that solidified the connections between us.\n\nReflecting on today's journal entry, I am grateful for the diverse personalities that make up our tight-knit group. Each individual brings something unique to the table, and the synergy of our friendship enhances the tapestry of our lives. Today was a reminder that true wealth lies in the richness of meaningful relationships."
entry_2 = "A chapter in John's journal unfolded with a blend of introspection and serendipity. The day began with the gentle cadence of rain tapping on his window, casting a reflective mood upon his morning coffee ritual. With each sip, thoughts meandered through memories and aspirations, creating a canvas of contemplation. As the rain subsided, John embarked on a solitary stroll through the city streets, where the urban symphony played softly in the background. The bustling cafes, each with its unique character, became waypoints for moments of solitude amidst the crowd. Conversations with strangers and glimpses of vibrant street art added layers to the day's narrative. The afternoon found John immersed in the pages of a novel, transported to distant lands and eras by the power of words. The cozy corner of his favorite bookstore became a refuge, allowing the imagination to wander freely. Evening brought an unexpected reunion with an old friend, turning a routine day into a tapestry of shared stories and laughter. A spontaneous dinner at a familiar diner became a celebration of camaraderie, reminiscing about the journey from youth to the present. The day concluded with John capturing fleeting thoughts in his journal, a testament to the ever-evolving story of his life. Gratitude filled his heart for the simple joys, chance encounters, and the beauty found in the ordinary. As he closed the journal, the city's lights twinkled outside, echoing the sentiment that each day, no matter how unassuming, holds its own unique magic."


personalities_list = [
    "John - A compassionate soul with a penchant for helping others, John is known for his kindness and empathetic nature.",
    "Emily - An adventurous spirit, Emily thrives on exploring the unknown and embraces challenges with a positive attitude.",
    "Daniel - With a keen intellect and a love for learning, Daniel is the perpetual student, always seeking knowledge and wisdom.",
    "Sophia - Graceful and poised, Sophia exudes elegance in everything she does, from her fashion choices to her thoughtful gestures.",
    "Michael - A charismatic individual, Michael has a natural ability to bring people together, making every gathering a lively affair.",
    "Olivia - A free spirit with an artistic flair, Olivia expresses herself through creativity, be it in art, music, or literature.",
    "William - Driven by ambition, William is a go-getter who approaches challenges with determination and a strong work ethic.",
    "Ava - Radiating positivity, Ava's infectious laughter and warm smile brighten the darkest of days, making her a joy to be around.",
    # Add more personalities as needed
]

print(llm_ai.rank_people(personalities_list, "Find a person who is adventurous and loves to explore."))